name: Build-Test

runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - run: bun install
    - name: Install Playwright
      run: bunx playwright install --with-deps

    - run: bun run build

    - name: Checks
      run: bun run check

    - name: Playwright tests
      run: bun test
    - name: Upload Playwright test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-results
        path: test-results