name: Build-Test

runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - run: bun install
      shell: bash
    - name: Install Playwright
      run: bunx playwright install --with-deps
      shell: bash

    - run: bun run build
      shell: bash

    - run: bun run check
      shell: bash

    - run: bun test
      shell: bash
    - name: Upload Playwright test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-results
        path: test-results