name: CI Without Deploy

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]
    types: [closed]

permissions:
  contents: write
jobs:
  build-test:
    if: github.event.push || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/build-test