name: CI Without Deploy

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build-test.yml