name: CI Without Deploy

on:
  push:
    branches-ignore: [ main ]

permissions:
  contents: write
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/build-test